/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectfinal;

import javafx.application.Application;
import javafx.stage.Stage;
import projectfinal.Scene.MainScene;

public class App extends Application {
    @Override
    public void start(Stage PrimaryStage) {
        Stage stage;
        stage = PrimaryStage;
        stage.setTitle("MovieMates");

        MainScene mainsScene = new MainScene(stage);
        mainsScene.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
